package com.neighborparking.common.error;

public enum ErrorCode {
    BAD_REQUEST,
    VALIDATION_FAILED,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    DEV_LOGIN_DISABLED,
    INVALID_STATE_TRANSITION,
    BOOKING_TIME_CONFLICT,
    SLOT_NOT_AVAILABLE,
    VEHICLE_NOT_AVAILABLE,
    SPACE_NOT_APPROVED,
    OWNER_CANNOT_BOOK_OWN_SPACE,
    DUPLICATE_REVIEW,
    INTERNAL_ERROR
}
